version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - make install

  pre_build:
    commands:
      - echo "Linting code with pylint..."
      - make lint
      - echo "Formatting code with black..."
      - make format